name:                vscle
version:             0.1.0.0
author:              "Benjamin Flin"
maintainer:          "benajmin.flin@peratonlabs.com"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md file 

dependencies:
- base >= 4.7 && < 5

executables:
  cle-lang-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lsp
    - zeromq4-haskell
    - text
    - lens
    - hslogger
    - transformers
